services:
  - type: web
    name: spring-backend
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt

    # No build/start commands needed since Dockerfile handles it
    buildCommand: ""
    startCommand: ""

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend-db
          property: connectionString
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: PORT
        value: 8080

databases:
  - name: backend-db
    plan: free